server:
  port: 10086
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中作为服务的id标识（serviceId）
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要写其它Server的地址。
      defaultZone: http://127.0.0.1:10087/eureka, http://127.0.0.1:10086/eureka
    register-with-eureka: false # 不注册自己
    fetch-registry: false #不拉取服务
    registry-fetch-interval-seconds: 30 #每隔30秒会重新获取并更新数据
  instance:
    lease-expiration-duration-in-seconds: 90 #如果超过90秒没有发送心跳，EurekaServer就会认为该服务宕机
    lease-renewal-interval-in-seconds: 30 #每个30秒服务会向注册中心发送一次心跳